// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  PhonegapApp.Message = (function(_super) {
    __extends(Message, _super);

    Message.resourceName = 'message';

    Message.storageKey = 'messages';

    Message.encode('content', 'id');

    Message.hasMany('responses');

    Message.belongsTo('user');

    function Message() {
      Message.__super__.constructor.apply(this, arguments);
      this.set('response', this.buildResponse());
    }

    Message.prototype.buildResponse = function() {
      var response;
      response = new PhonegapApp.Response();
      response.set("message", this);
      return response;
    };

    Message.prototype.addResponse = function(response) {
      return this.get("responses").add(response);
    };

    return Message;

  })(PhonegapApp.Model);

}).call(this);
