// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  PhonegapApp.MessagesController = (function(_super) {
    __extends(MessagesController, _super);

    MessagesController.prototype.routingKey = 'messages';

    function MessagesController() {
      MessagesController.__super__.constructor.apply(this, arguments);
      this.setMessage();
      this.setSelectedUser(15);
    }

    MessagesController.prototype.index = function() {
      return this.set('messages', PhonegapApp.Message.get('all').sortedBy('id', 'desc'));
    };

    MessagesController.prototype.create = function() {
      var _this = this;
      this.message.set("user", PhonegapApp.currentUser);
      return this.message.save(function(errorSet, resultSet) {
        if (errorSet === void 0) {
          _this.messages.add(resultSet);
          return _this.setMessage();
        }
      });
    };

    MessagesController.prototype.setMessage = function() {
      var message;
      message = new PhonegapApp.Message();
      return this.set('message', message);
    };

    MessagesController.prototype.setSelectedUser = function(id) {
      var _this = this;
      return PhonegapApp.User.find(id, function(errorSet, response) {
        _this.set('selectedUser', response);
        PhonegapApp.set("currentUser", response);
        return _this.selectedUser.observeOnce('id', function(id) {
          return _this.setSelectedUser(id);
        });
      });
    };

    return MessagesController;

  })(PhonegapApp.ApplicationController);

}).call(this);
