// Generated by CoffeeScript 1.6.3
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  PhonegapApp.Model = (function(_super) {
    __extends(Model, _super);

    function Model() {
      _ref = Model.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Model.urlPrefix = 'http://ec2-54-194-12-190.eu-west-1.compute.amazonaws.com';

    Model.prototype.urlPrefix = 'http://ec2-54-194-12-190.eu-west-1.compute.amazonaws.com';

    Model.urlSuffix = '.json';

    Model.prototype.urlSuffix = '.json';

    Model.serializeAsForm = false;

    Model.persist(Batman.RailsStorage);

    return Model;

  })(Batman.Model);

}).call(this);
