// Generated by CoffeeScript 1.6.3
(function() {
  var PhonegapApp, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  PhonegapApp = (function(_super) {
    __extends(PhonegapApp, _super);

    function PhonegapApp() {
      _ref = PhonegapApp.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    PhonegapApp.resources('messages');

    PhonegapApp.root('messages#index');
    PhonegapApp.route('main.html', 'messages#index');

    return PhonegapApp;

  })(Batman.App);

  (typeof global !== "undefined" && global !== null ? global : window).PhonegapApp = PhonegapApp;

  Batman.Request.accessor('url', {
    get: function() {
      if (this.url.charAt(0) === "/") {
        return "." + this.url;
      }
      else {
        return this.url;
      }
    }, set: function(_, url) {
      return this.url = url;
    }
  });

}).call(this);
