// Generated by CoffeeScript 1.6.3
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  PhonegapApp.Response = (function(_super) {
    __extends(Response, _super);

    function Response() {
      _ref = Response.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Response.resourceName = 'response';

    Response.storageKey = 'responses';

    Response.urlNestsUnder('message');

    Response.encode('content');

    Response.belongsTo('user');

    Response.belongsTo('message');

    return Response;

  })(PhonegapApp.Model);

}).call(this);
