// Generated by CoffeeScript 1.6.3
(function() {
  var _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  PhonegapApp.ResponsesController = (function(_super) {
    __extends(ResponsesController, _super);

    function ResponsesController() {
      _ref = ResponsesController.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    ResponsesController.prototype.routingKey = 'responses';

    ResponsesController.prototype.create = function(message) {
      var response,
        _this = this;
      response = message.get("response");
      response.set("user", PhonegapApp.currentUser);
      return response.save(function(errorSet, resultSet) {
        if (errorSet === void 0) {
          message.set("response", message.buildResponse());
          return message.addResponse(resultSet);
        }
      });
    };

    return ResponsesController;

  })(PhonegapApp.ApplicationController);

}).call(this);
